### ISSUE TITLE
syntax errrors theorie_Property

### ISSUE THREAD

**Issue by 886419** [stasemsoft/softwarematerial#18]
https://stasemsoft.github.io/softwarematerial/docs/objects/theorie_Property

>     public int Minutes                  // Property
>     {
>         get { return seconds / 60 };    // Getter
>         set { seconds = value * 60 };   // Setter
 
I'm not a dotnet expert yet :) but the semicolons seem to belong inside the brackets.
Would be cool if we could test-compile examples automagically...

**Comment by coentjo** [comment]
Thanks! Changed it.
